name: editorconfig check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  editorconfig-check:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        php-version: [ '8.1' ]

    steps:
      -   name: Checkout code
          uses: actions/checkout@v4

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-version }}
            extensions: mbstring, intl
            coverage: yes

      -   name: php version
          run: php -v

      -   name: Install Composer dependencies
          run: composer install

      -   name: Run editorconfig check
          run: |
            vendor/bin/ec .
